module.exports = [
    {
        background: 'blue',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/human%20(man).png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'I',
        type: 'text',
        visible: true
    },
    {
        background: 'green',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/mulberry/square.svg',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'it',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/ok.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'okay',
        type: 'text',
        visible: true
    },
    {
        background: 'purple',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/mulberry/extra%20large.svg',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'more',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/point.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'that',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/mulberry/point%20,%20to.svg',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'you',
        type: 'text',
        visible: true
    },
    {
        background: 'pink',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/sclera/stop_7.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'dont',
        type: 'text',
        visible: true
    },
    {
        background: 'pink',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/wish%20for%20-%20want.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'want',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/tawasol/Big%20sister.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'big',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/sclera/small.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'little',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/tawasol/170-Eat%20F.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'eat',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/sclera/drink_1.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'drink',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/tawasol/65-Play.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'play',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/help%202.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'help',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/tawasol/Go%20(M).png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'go',
        type: 'text',
        visible: true
    },
    {
        background: 'purple',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/different.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'different',
        type: 'text',
        visible: true
    },
    {
        background: 'pink',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/feel%201.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'feel',
        type: 'text',
        visible: true
    },
    {
        background: 'pink',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/to%20make%20happy.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'happy',
        type: 'text',
        visible: true
    },
    {
        background: 'purple',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/sclera/mad%20box.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'mad',
        type: 'text',
        visible: true
    },
    {
        background: 'green',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/finish.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'finished',
        type: 'text',
        visible: true
    },
    {
        background: 'pink',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/arasaac/inside.png',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'in',
        type: 'text',
        visible: true
    },
    {
        background: 'white',
        column: 1,
        image: 'https://storage.googleapis.com/symbols/mulberry/hot%20person.svg',
        page: 'homepage',
        profile: 'default',
        row: 1,
        speak: true,
        text: 'am',
        type: 'text',
        visible: true
    },
]